version: '3'
services:
  web:
    build: .
    container_name: "sclng_backend"
    volumes:
      - ./:/go/src/github.com/IhsenCharfi/sclng_backend
    ports:
      - "3000:3000"
    command: reflex -r '\.go$$' -s -- sh -c 'go build -buildvcs=false && ./sclng_backend'
    stop_signal: SIGKILL
